name: update-lives
on:
  push:
  
  workflow_dispatch:
  
jobs:
  build:
    name: update live files by ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Prepare Configuration
      run: |
         cd $GITHUB_WORKSPACE
         ls
