name: update-lives
on:
  push:
  
  workflow_dispatch:
  
jobs:
  build:
    name: update live files by ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Prepare Configuration
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         cd $GITHUB_WORKSPACE
         pip3 install requests
         pip3 install opencv-python
         pip3 install bs4
         pip3 install translate
         sudo apt-get install ffmpeg
         python3 udp_iptv3.0.py
         echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
         git am -s "update:"${{ env.BUILD_TIME }}
